### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by godcong** [src-d/proteus#107]
the example command is only find the go path

**Comment by g13013** [comment]
Is the support for Go modules planned anytime soon?

**Comment by godcong** [comment]
does #24661 will fix this issues?
if it is this can closed,:)
@dennwc

**Comment by dennwc** [comment]
No, we still need few things on Proteus side to support modules correctly.

**Comment by OGKevin** [comment]
> No, we still need few things on Proteus side to support modules correctly.

Do you mind sharing what needs to be done? Maybe we can help. I just landed on this tool and I would also like to use it. But I need go module support. 

> We will switch to it, of course, but we will postpone this change until Go 1.12 is released.

Go 1.12 got released, should this be picked up?

**Comment by dennwc** [comment]
> Do you mind sharing what needs to be done?

We just need to make sure that Proteus uses updated dependencies to parse Go files, so it's able to resolve projects with modules.

> Maybe we can help.

This would be great :) I'll try to check this when I have time, but it might take a while.

**Comment by godcong** [comment]
i think at first this project self need update to go module :)

**Comment by godcong** [comment]
Any progress? i want to close this issue...

**Comment by godsoul** [comment]
Go 1.13 got released, : (

**Comment by inhuman** [comment]
Go 1.14 got released :((

**Comment by bendoerr** [comment]
fyi - https://github.com/src-d/proteus/issues/113 - probably never going to get support in it's current state

**Comment by godcong** [comment]
Someone tried to maintain the code：
    https://github.com/charm-jp/proteus
