### ISSUE TITLE
error: github.com/gogo/protobuf is not installed

### ISSUE THREAD

**Issue by azhang** [src-d/proteus#115]
go get -v gopkg.in/src-d/proteus.v1/...
    go get -u github.com/gogo/protobuf/...
    proteus -f protoes -p github.com/whatever/common  

responds with

    github.com/gogo/protobuf is not installed

**Comment by azhang** [comment]
had to get out of my project directory so it could actually clone src into into $GOPATH

**Comment by wimmerX** [comment]
> had to get out of my project directory so it could actually clone src into into $GOPATH

I have encounter the same question,what can I do for it ?
