### ISSUE TITLE
Problem with type `int`

### ISSUE THREAD

**Issue by erizocosmico** [src-d/proteus#40]
## Problem 

There is no `int` in protobuf, only `int32` and `int64`. Then, when we generate the .proto file we have to choose between one of them. Right now, the choice is `int32`.

Problem is, when doing the gogoproto step, it takes into account the proto file, and not the Go source code, and thus what it thinks is that the type is an `int32` instead of `int`.

## Steps to reproduce:

* Generate this:
```go
package foo

//proteus:generate
type Foo struct {
        A int
}
```

## Fix

* Set custom type on proto when the type has no direct translation in protobuf
* Change the transation of `int` to `int64` and `uint` to `uint64` in protobuf

## Caveats

* It probably happens as well with `time.Duration` and all the types that don't have a clear direct mapping (all other ints besides signed and unsigned `int32` and `int64`)

**Comment by Serabe** [comment]
We can error if we see type `int` that user should change it to `int32` or `int64`.

**Comment by erizocosmico** [comment]
This was fixed, right?

**Comment by Serabe** [comment]
Yes, but since we are using `services` it is not closed automagically.

**Comment by shurcooL** [comment]
What are you referring to with `services`?

**Comment by Serabe** [comment]
`services` branch.

**Comment by shurcooL** [comment]
I see.

I'm not familiar with the details, so this suggestion might be off base, but have you considered making that branch the default branch of this repository? If you're using it that way.

Then, when a PR merged into `services` branch says "fixes" some issue, it will get closed by github.

**Comment by erizocosmico** [comment]
We were using `services` branch as a "development" branch until all the pending issues and the gRPC services implementation were finished. It should be finished today or tomorrow and we'll merge it into master.
