### ISSUE TITLE
method redeclared: Size

### ISSUE THREAD

**Issue by alban** [src-d/proteus#74]
The method `Size()` is defined both in the source and in the generated file:

```
# github.com/weaveworks/scope/report
report/generated.pb.go:57: undefined: "github.com/weaveworks/scope/vendor/github.com/golang/protobuf/proto".ProtoPackageIsVersion2
report/generated.pb.go:151: undefined: "github.com/weaveworks/scope/vendor/github.com/golang/protobuf/proto".RegisterType
report/generated.pb.go:152: undefined: "github.com/weaveworks/scope/vendor/github.com/golang/protobuf/proto".RegisterType
report/generated.pb.go:153: undefined: "github.com/weaveworks/scope/vendor/github.com/golang/protobuf/proto".RegisterType
report/generated.pb.go:1250: method redeclared: Counters.Size
	method(Counters) func() int
	method(*Counters) func() int
report/generated.pb.go:1256: method redeclared: EdgeMetadatas.Size
	method(EdgeMetadatas) func() int
	method(*EdgeMetadatas) func() int
report/latest_map_generated.go:47: method redeclared: StringLatestMap.Size
	method(*StringLatestMap) func() int
	method(StringLatestMap) func() int
report/latest_map_generated.go:199: method redeclared: NodeControlDataLatestMap.Size
	method(*NodeControlDataLatestMap) func() int
	method(NodeControlDataLatestMap) func() int
report/node_set.go:100: method redeclared: NodeSet.Size
	method(*NodeSet) func() int
	method(NodeSet) func() int
report/sets.go:71: method redeclared: Sets.Size
	method(*Sets) func() int
	method(Sets) func() int
report/generated.pb.go:153: too many errors
```

Note: I am using [this branch in Scope](https://github.com/kinvolk/scope/commits/alban/proteus) for testing.

**Comment by Serabe** [comment]
Now we add the options for gogo/protobuf to generate a `ProtoSize` method instead of `Size`.

Thank you for the report!

**Comment by Serabe** [comment]
By the way, a new version has been released with this fix. You can get it with `go get -u gopkg.in/src-d/proteus.v1`.

**Comment by alban** [comment]
@Serabe Thanks! The errors about the method `Size` are gone now.

I still have the errors about undefined `ProtoPackageIsVersion2` and `RegisterType`. Do you have any tip to find out what it is about? I am vendoring github.com/gogo/protobuf from git master

**Comment by Serabe** [comment]
It seems it is looking for those in `golang/protobuf`. Do you have a branch I can use to reproduce this in local?

**Comment by alban** [comment]
Indeed, both golang/protobuf and gogo/protobuf are vendored via `vendor/manifest`. I am using [this branch](https://github.com/kinvolk/scope/commits/alban/proteus). `make` will build Scope in Docker containers.

The generated file (`report/generated.pb.go`) imports both versions of `proto` (and some imports are duplicated imports):

<details>

```
package report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"
```
</details>

**Comment by Serabe** [comment]
Ok, I'll try to get some time to look into this, but I'm attending some conferences, so that might mean my time is reduced.

**Comment by Serabe** [comment]
You need to update your vendored files for protobuf. After that, I opened #76 to keep fixing things.
