### ISSUE TITLE
Make Scope work with Proteus

### ISSUE THREAD

**Issue by Serabe** [src-d/proteus#76]
Repo: https://github.com/kinvolk/scope/tree/alban/proteus

The problem is related to `map[string]SomeStruct`, given the value type is not nullable and protobuf expects so. I'm investigating an option for `gogo/protobuf` to allow a value type to be nullable in a map.

Current problems:
- report/generated.pb.go:535: cannot convert nil to type Metric
- report/generated.pb.go:545: cannot convert nil to type Metric
- report/generated.pb.go:1057: cannot convert nil to type Node
- report/generated.pb.go:1067: cannot convert nil to type Node
- report/generated.pb.go:1085: cannot convert nil to type Control
- report/generated.pb.go:1095: cannot convert nil to type Control
- report/generated.pb.go:1113: cannot convert nil to type MetadataTemplate
- report/generated.pb.go:1123: cannot convert nil to type MetadataTemplate
- report/generated.pb.go:1141: cannot convert nil to type MetricTemplate
- report/generated.pb.go:1151: cannot convert nil to type MetricTemplate

**Comment by alban** [comment]
@Serabe Thanks for looking at this!

Upstream repo: https://github.com/weaveworks/scope/
Scope issue about trying Proteus: https://github.com/weaveworks/scope/issues/2433

/cc @2opremio @schu @iaguis

**Comment by Serabe** [comment]
Updated text and removed the EPIC label since they are all the same problem.

**Comment by Serabe** [comment]
@alban I submitted this morning a PR to alban/proteus https://github.com/kinvolk/scope/pull/5

Basically, I fixed all the problems I found and made a new release. Then, I did a `make clean` to make sure everything was removed properly and tried again. I also added some files from gogo/protobuf that are really needed (those can be found in the PR).

Thank you!
