### ISSUE TITLE
enum values are not generated correctly when the first value is discarded

### ISSUE THREAD

**Issue by smola** [src-d/proteus#86]
It seems that if you define an enum using `_ = iota`, the values in Go will start at `1`, while the generated proto will start at `0`.

I couldn't really verify this yet.
This is where I'm seeing divergences:
https://github.com/bblfsh/sdk/blob/master/uast/uast.go
https://github.com/bblfsh/sdk/blob/master/uast/generated.proto
(`Roles` enum)

**Comment by erizocosmico** [comment]
As a workaround, you can do `Foo = 1 + iota` instead of using `_ = iota`.

**Comment by smola** [comment]
@erizocosmico :+1: thanks!

**Comment by erizocosmico** [comment]
@smola on a second thought, we can't do anything to solve that on the proteus side. Protobuf enums must start at 0 (https://developers.google.com/protocol-buffers/docs/proto3#enum) If you want the enums to match you'll have to start at 0.

**Comment by erizocosmico** [comment]
One thing you could do is naming the invalid value, instead of using `_`:

```go
type Role uint64

const (
  Invalid Role = iota

  Foo
  Bar
  ...
)
```

**Comment by erizocosmico** [comment]
Ping @smola

**Comment by Serabe** [comment]
Ping @smola

**Comment by abeaumont** [comment]
looks good to me
